#!/usr/bin/env python3
"""GlassBox AI Agent — reads a GitHub issue and generates a fix with tests."""

import json, os, subprocess, sys

from openai import OpenAI


def run(cmd):
    """Run shell command and return result."""
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def gh(args):
    """Run gh CLI command."""
    return run(f"gh {args}")


def comment(issue, repo, msg):
    """Comment on a GitHub issue."""
    gh(f'issue comment {issue} --repo {repo} --body "{msg}"')


def main():
    issue_number = sys.argv[1]
    repo = os.environ.get("GITHUB_REPOSITORY", "glassbox-ai-labs/glassbox-ai")

    # 1. Read issue
    result = gh(f"issue view {issue_number} --repo {repo} --json title,body")
    issue = json.loads(result.stdout)
    print(f"Issue #{issue_number}: {issue['title']}")

    # 2. Comment: picked up
    comment(issue_number, repo,
            "🤖 **Agent picked this up.** Analyzing the issue and generating a fix...")

    # 3. Read source files
    source_files = {}
    for path in [
        "src/glassbox/__init__.py",
        "src/glassbox/server.py",
        "src/glassbox/orchestrator.py",
        "src/glassbox/trust_db.py",
        "tests/test_glassbox.py",
    ]:
        with open(path) as f:
            source_files[path] = f.read()

    # 4. Call OpenAI — generate the fix
    client = OpenAI()
    prompt = f"""You are a senior Python developer fixing a GitHub issue for GlassBox AI.

Issue #{issue_number}: {issue['title']}
{issue['body']}

Current source files:
{json.dumps(source_files, indent=2)}

Return ONLY valid JSON with this exact structure:
{{
  "changes": [
    {{"file": "path/to/file.py", "old": "exact string to replace", "new": "replacement string"}}
  ],
  "test_code": "def test_N_description():\\n    ...a complete pytest function...",
  "summary": "one-line commit message"
}}

Rules:
- Minimal fix. Max 5 lines changed total.
- "old" must be an EXACT substring of the current file content.
- Include ONE test function that verifies the fix.
- Follow existing code style exactly.
- Do not change comments or docstrings unless the issue requires it."""

    response = client.chat.completions.create(
        model="gpt-4o",
        temperature=0.1,
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"},
    )
    fix = json.loads(response.choices[0].message.content)
    print(f"Fix: {fix['summary']}")

    # 5. Comment: applying
    comment(issue_number, repo,
            "🔧 **Fix generated.** Applying changes and running tests...")

    # 6. Create branch
    branch = f"agent/issue-{issue_number}"
    run(f"git checkout -b {branch}")

    # 7. Apply code changes
    for change in fix["changes"]:
        with open(change["file"]) as f:
            content = f.read()
        if change["old"] not in content:
            comment(issue_number, repo,
                    f"❌ **Agent error:** Could not find target string in `{change['file']}`. Manual fix needed.")
            sys.exit(1)
        content = content.replace(change["old"], change["new"], 1)
        with open(change["file"], "w") as f:
            f.write(content)

    # 8. Append test
    if fix.get("test_code"):
        with open("tests/test_glassbox.py", "a") as f:
            f.write("\n\n" + fix["test_code"] + "\n")

    # 9. Run tests
    test_result = run("python -m pytest tests/test_glassbox.py -v --tb=short")
    print(test_result.stdout)

    if test_result.returncode != 0:
        comment(issue_number, repo,
                f"❌ **Tests failed.** Agent fix did not pass.\\n\\n```\\n{test_result.stdout[-500:]}\\n```")
        sys.exit(1)

    # 10. Commit and push
    run("git add -A")
    run(f'git commit -m "fix: {fix["summary"]} (agent-fix #{issue_number})"')
    push = run(f"git push origin {branch}")
    print(push.stderr)

    # 11. Create PR
    pr_body = f"""Closes #{issue_number}

## Changes
{fix['summary']}

## Generated by
🤖 **GlassBox AI Agent** — automated fix triggered by `agent` label.

## Tests
✅ All unit tests passing.
CI pipeline will verify integration tests and Docker build."""

    pr_result = gh(
        f'pr create --repo {repo} --base main --head {branch} '
        f'--title "fix: {fix["summary"]}" '
        f'--body "{pr_body}"'
    )
    pr_url = pr_result.stdout.strip()
    print(f"PR created: {pr_url}")

    # 12. Comment on issue: done
    comment(issue_number, repo,
            f"✅ **PR ready for review:** {pr_url}\\n\\n"
            f"**Changes:** {fix['summary']}\\n"
            f"**Tests:** ✅ All passing\\n\\n"
            f"Waiting for CI pipeline and maintainer approval.")


if __name__ == "__main__":
    main()
